// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVRWuTp9Ci3NHrU6TqJ_-03NrRJEm_HpM',
    appId: '1:629013002194:web:193dc721cd8aeefda0ba0b',
    messagingSenderId: '629013002194',
    projectId: 'class-17-1c83f',
    authDomain: 'class-17-1c83f.firebaseapp.com',
    storageBucket: 'class-17-1c83f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SsXCjOf6CJvQWEiJirnC2WQLATwUqFU',
    appId: '1:629013002194:android:e61f32fcf3607a1da0ba0b',
    messagingSenderId: '629013002194',
    projectId: 'class-17-1c83f',
    storageBucket: 'class-17-1c83f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtZy3ONIB_vnV8U2pFFWY9hDQ7xHmmXho',
    appId: '1:629013002194:ios:4e8f115d1eec970da0ba0b',
    messagingSenderId: '629013002194',
    projectId: 'class-17-1c83f',
    storageBucket: 'class-17-1c83f.appspot.com',
    iosBundleId: 'com.example.class17',
  );
}
